### ISSUE TITLE
Length Weighted Rose Diagrams

### ISSUE THREAD

**Issue by psleath** [BjornNyberg/NetworkGT#1]
When producing a rose diagram through the rose diagram plots tool, the final diagram doesn't appear when trying to use the weighted field feature. I'm trying to weight my fractures by length attribute. Can you help please?

**Comment by BjornNyberg** [comment]
In order to resolve this issue I would need to learn more regarding the dataset. Is the data in a projected coordinate system, scale of the dataset, etc...? Do you encounter the same problem when using the weighted field option on the Hartland Point fracture dataset example? If the problem persists please contact me directly (available in the user-guide.pdf).
