### ISSUE TITLE
Error with plot

### ISSUE THREAD

**Issue by MarcoMercu** [BjornNyberg/NetworkGT#10]
Hello, thank you very much for the code you developed. I am using v.1.0 in QGIS and it works fine. 
I have an issue that I can't solve. When I try to plot something by using for example  "Histogram" or "Rose Diagram" I obtain the following error: 

"AttributeError: 'Figure' object has no attribute 'show'"

I also tried to update plotly to its latest version but it does not work.

Can you help me, please?

Thank you in advance,
Marco

**Comment by BjornNyberg** [comment]
@MarcoMercu Have you used the Configure NetworkGT script? Plotly needs to be updated to at least 'plotly==4.12.0'

**Comment by MarcoMercu** [comment]
Thanks for the answer. Yes, I followed the installation procedure for MacOS ad described in the Wiki and Plotly is updated but I could not solve the issue..

**Comment by BjornNyberg** [comment]
@MarcoMercu If you open the QGIS Python Console and type the following what version of plotly do you see?

`import plotly`

`plotly.__version__`

![image](https://user-images.githubusercontent.com/37108459/99810609-43313180-2b44-11eb-8bf6-ab8a21536121.png)
![image](https://user-images.githubusercontent.com/37108459/99810733-6f4cb280-2b44-11eb-8186-1db2dfd968e6.png)

**Comment by MarcoMercu** [comment]
Here is the problem.. It turns out I have a previous version installed (3.9.0). 
I installed the python modules by typing "pip install ...." in the terminal and QGIS does not look at the same python version. How can I install the python modules in QGIS? 
Thanks again for your help

**Comment by BjornNyberg** [comment]
Unfortunately I do not have a MacOSX and am not sure on the correct procedure. I do know that the newest QGIS version does contain plotly version 4.x.x and that would be a start. Otherwise I would suggest taking a look at this forum https://gis.stackexchange.com/questions/351280/installing-python-modules-for-qgis-3-on-mac . If you do figure out a solution and would like to share those we can add that to the installation guide but considering this is not an issue with the NetworkGT plugin I will close this bug report for now.
