### ISSUE TITLE
Error 000732 using Topology Parameters

### ISSUE THREAD

**Issue by travertinegirl** [BjornNyberg/NetworkGT#16]
Hi Bjorn,

I've come across an issue using Topology Parameters on my computer, for your tutorial example, and a trace map that I generated. I run ArcMap 10.8 with Python 2.7. The issue is that when I run is something to do with the Excel files created: 

ERROR 000732: Input Excel File: Dataset temp_table.xls does not exist or is not supported
Failed to execute (ExcelToTable).
(attached is an image of the dialogue box: ![error2](https://user-images.githubusercontent.com/82035075/113709966-6a4b6280-96e3-11eb-83b1-a1da757cc7f3.png))

I checked a few things like the file roots, but they seem to be OK with backslashes and no spaces in file names. I checked this problem with a colleague of mine and there seemed to be no problem when they ran the tutorial with their computers. However, when I sent them shapefiles with the branches, nodes and interpretation boundary which I generated with my computer- they received the same error. So that led me to think that my ArcMap version is not compatible but I'm not sure about this. Either way I cannot use Topology parameters at present.

Can you help me out? Thanks!

**Comment by BjornNyberg** [comment]
Hi @travertinegirl 

I believe this error has to do with the installation procedure (i've updated a new master version that will create an Error Log.txt file in the scripts folder for confirmation). 

Unfortunately python version 2.7 and pip used to install modules has been discontinued since January 2021. This means that the module xslxwriter is not installed correctly with the current installation procedure. I would recommend using the QGIS version with instructions available [here](https://github.com/BjornNyberg/NetworkGT/wiki/Installation). 

Your other alternative is to manually install the required modules and/or trying using Anaconda.

Cheers,
Björn

**Comment by travertinegirl** [comment]
Hi Bjorn,

Thanks for the quick reply. So, that's interesting because I originally I used python 3.6 (i think this is the latest version with anaconda too) and received this error when running topology parameters:
![python3 6error](https://user-images.githubusercontent.com/82035075/113872054-ce3d5c00-97b3-11eb-8c1e-c0346468c7ec.png)

So at the moment will Arcmap not work with Network GT at all and that QGIS is the only option?

Thank you,
travertinegirl

**Comment by BjornNyberg** [comment]
Hi @travertinegirl 

That error should also be fixed in the new master version (download the .zip file again from github), however, I cannot guarantee that all the scripts will work. The reason being is that the syntax is different between Python 2.x and Python 3.x and ArcMap 10.6? < use Python 2.x.

I myself do not use ArcMap for NetworkGT anymore but leave it on GitHub as an archive.

Bjorn

**Comment by brick00** [comment]
Hey there! 

I am having the same issue here trying to run topology parameters (000732). I am working with a very large volume of nodes and branches (~1.5M) on arcmap 10.7.1. I think actually this error could be due to the number features exceeding the maximum number of excel rows (1,048,576). I am working with NetworkGT 0.99 and the python version i have got installed is Python 2.7.16. 

Worth saying that I had no problems running topology parameters for smaller datasets - I have successfully run the tool with a dataset with ~850k nodes.

Is there a workaround that does not foresee splitting data up into sections?

**Comment by BjornNyberg** [comment]
@brick00

No unfortuantely i do not believe there is a solution other than as you suggest, split the data into sections and later merge the results.
