### ISSUE TITLE
"Could not find Sample" error 

### ISSUE THREAD

**Issue by MaryiR** [BjornNyberg/NetworkGT#19]
Hi Bjorn,

I've tried to calculate the topology parameters uning Qgis. The algoritm seems to read the nodes, branches and the gird. However, it does not calculate this parameters and return "Could not find Sample" like the image shows. ¿Could you help me to fix it?

Thank you,  

![Network-gt](https://user-images.githubusercontent.com/70228075/161657621-8379039e-8552-45d6-a4bc-fc8e2c3aa9be.png)

**Comment by BjornNyberg** [comment]
@MaryiR 

This error indicates that it has trouble finding the sample id number in the pandas attribute table that is created in the background. The only reason I can think of looking at only the execution file above is that your working with memory files and if you close a QGIS project and reopen it those memory files (branches, nodes) will disappear. 

Otherwise could you perhaps provide an example to replicate this problem?

**Comment by MaryiR** [comment]
Thanks for your answer. However I am working with saved files and not with the temporary ones. The error appears when using the sampling grid but if I use the whole interpretation boundary it does calculate the topological parameters, however these are not representative because it calculates only one value for the whole interpretation boundary.

On the other hand, the generated layers of nodes and branches have a value of 0 for each row in the Sample_No column. If I modify the attribute table by giving it an id in "sample_No" the generated map is not representative of the intensity like you could see in the image.

Thank you, 
![intensity](https://user-images.githubusercontent.com/70228075/161797023-a66ba0ad-4b1f-4c49-b8fd-a30adf5d351e.png)




Thank you.

**Comment by BjornNyberg** [comment]
@MaryiR 

Hmm based soley on the image that you provided it would appear that the branches and nodes tools was not based on the sampling grid because there only appears to be two "I" node for each "I-I" line (you would expect multiple I nodes considering each sampling grid would intersect the same fracture line at different localities). 

Unfortunately, I cannot be of more help without seeing the actual data. If you would like you can send the data to my email at bjorn.nyberg@uib.no, please feel free to do so.

Cheers,
Bjorn

**Comment by IasonasPF** [comment]
I encountered the same issue. Was this ever resolved and if so. How?

**Comment by BjornNyberg** [comment]
Hi @IasonasPF
If I remember correctly there was an issue with the datasets not being in a projected coordinate system. If however this is not an issue with your dataset, then please send a sample copy to me so that i nay be able to reproduce the error. 
Cheers
Bjorn
