### ISSUE TITLE
Error using topology parameters

### ISSUE THREAD

**Issue by FelipeFuentesCarrasco** [BjornNyberg/NetworkGT#20]
Hello Bjorn, along with saying hello, I am writing to you because we have a problem using the topology parameters in Arcgis, it appears that we have few parameters, that at least 1 is expected, I am attaching the screenshots (they are in Spanish, yes). I remain attentive to anything and in advance thank you very much.

![Error 1](https://user-images.githubusercontent.com/105308112/167943944-89ed08e7-8bd8-4f01-8704-098e8e0426a0.jpg)
![Error 2](https://user-images.githubusercontent.com/105308112/167943946-92fc9aa7-4f59-48fb-a189-6eb3246fe4da.jpg)

**Comment by BjornNyberg** [comment]
Hi @FelipeFuentesCarrasco ,

Unfortunately due to the limited information associated with the error message, I can not be of much help. If you want, send me and email and perhaps we can have a quick meeting. 

Otherwise I would suggest in the future to migrate your work to QGIS. The current ArcGIS version of NetworkGT is based on Python 2 which is no longer supported, so it may be associated with that change as well.

Cheers,
Bjorn

**Comment by FelipeFuentesCarrasco** [comment]
Hi Bjorn, thanks for your reply, I don´t have your email, mine es felipe.fuentes@sernageomin.cl, it would´ve great if we could meet, to see if it is an arcgis problem or an user problem, otherwise we could try it on Qgis.

Thank you very much.

Cheers,
Felipe

**Comment by BjornNyberg** [comment]
Hi @FelipeFuentesCarrasco 

Find my email at the end of the wiki page https://github.com/BjornNyberg/NetworkGT/wiki

Cheers
Björn
